/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.espe.edu.proyecto.view;

import ec.espe.edu.proyecto.model.IPersonal;
import javax.swing.ImageIcon;

/**
 *
 * @author Cristian Arauz
 */
public class JfrmMenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form JfrmMenu
     */
    public JfrmMenuAdmin() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Video games");
        this.setIconImage(new ImageIcon(getClass().getResource("/ec/espe/edu/imagenes/iconSystem.png")).getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        JbutSearch = new javax.swing.JButton();
        JbutRemove = new javax.swing.JButton();
        JbutCrateUser = new javax.swing.JButton();
        JbutCreateConsola = new javax.swing.JButton();
        JbutReturn = new javax.swing.JButton();
        JbutExit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Bienvenido Administrador");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 280, 30));

        JbutSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/espe/edu/imagenes/vistastock.png"))); // NOI18N
        JbutSearch.setToolTipText("Presione para buscar en el stock");
        JbutSearch.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JbutSearch.setBorderPainted(false);
        JbutSearch.setContentAreaFilled(false);
        JbutSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbutSearchActionPerformed(evt);
            }
        });
        getContentPane().add(JbutSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 120, 130));

        JbutRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/espe/edu/imagenes/delete.png"))); // NOI18N
        JbutRemove.setToolTipText("Presione para borrar un articulo");
        JbutRemove.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JbutRemove.setBorderPainted(false);
        JbutRemove.setContentAreaFilled(false);
        getContentPane().add(JbutRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 120, 140));

        JbutCrateUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/espe/edu/imagenes/iconuser.png"))); // NOI18N
        JbutCrateUser.setToolTipText("Presione para crear un usuario");
        JbutCrateUser.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JbutCrateUser.setBorderPainted(false);
        JbutCrateUser.setContentAreaFilled(false);
        JbutCrateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbutCrateUserActionPerformed(evt);
            }
        });
        getContentPane().add(JbutCrateUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 120, 120));

        JbutCreateConsola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/espe/edu/imagenes/iconconsola.png"))); // NOI18N
        JbutCreateConsola.setToolTipText("Presione para ingresar al stock");
        JbutCreateConsola.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JbutCreateConsola.setBorderPainted(false);
        JbutCreateConsola.setContentAreaFilled(false);
        JbutCreateConsola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbutCreateConsolaActionPerformed(evt);
            }
        });
        getContentPane().add(JbutCreateConsola, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 130, 130));

        JbutReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/espe/edu/imagenes/retorna.png"))); // NOI18N
        JbutReturn.setToolTipText("Presione para volver al menu anterior");
        JbutReturn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JbutReturn.setBorderPainted(false);
        JbutReturn.setContentAreaFilled(false);
        JbutReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbutReturnActionPerformed(evt);
            }
        });
        getContentPane().add(JbutReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 110, 70));

        JbutExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/espe/edu/imagenes/exits.png"))); // NOI18N
        JbutExit.setToolTipText("Presione para salir del sistema");
        JbutExit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 0, 0), null, null));
        JbutExit.setBorderPainted(false);
        JbutExit.setContentAreaFilled(false);
        JbutExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbutExitActionPerformed(evt);
            }
        });
        getContentPane().add(JbutExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 130, 130));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Crear Usuario");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 100, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Buscar Inventario");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 130, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Crear Inventario");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 130, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Borrar Articulo");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 110, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Retornar");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 70, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Salir");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 50, 20));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/espe/edu/imagenes/imprimir.png"))); // NOI18N
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 70, 60));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Imprimir");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/espe/edu/imagenes/fondo verde.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JbutExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbutExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_JbutExitActionPerformed

    private void JbutCrateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbutCrateUserActionPerformed
        JfrmCreateUser jfrmCreateUser = new JfrmCreateUser();
        jfrmCreateUser.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JbutCrateUserActionPerformed

    private void JbutReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbutReturnActionPerformed
        JfrmMain jfrmMain = new JfrmMain();
        jfrmMain.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JbutReturnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JbutCreateConsolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbutCreateConsolaActionPerformed
        
    }//GEN-LAST:event_JbutCreateConsolaActionPerformed

    private void JbutSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbutSearchActionPerformed
        JfrmShourt jfrmShourt = new JfrmShourt();
        jfrmShourt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JbutSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfrmMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfrmMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfrmMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfrmMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfrmMenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbutCrateUser;
    private javax.swing.JButton JbutCreateConsola;
    private javax.swing.JButton JbutExit;
    private javax.swing.JButton JbutRemove;
    private javax.swing.JButton JbutReturn;
    private javax.swing.JButton JbutSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
