/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.espe.edu.proyecto.view;

import ec.espe.edu.proyecto.model.IPersonal;

/**
 *
 * @author Cristian Arauz
 */
public class JfrmCreateUser extends javax.swing.JFrame {

    /**
     * Creates new form JfrmCreateUser
     */
    public JfrmCreateUser() {
        initComponents();
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        JbutCreate = new javax.swing.JButton();
        JbutNuevo = new javax.swing.JButton();
        JbutReturn = new javax.swing.JButton();
        JbutExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/espe/edu/imagenes/iconuser.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        txtName.setToolTipText("Ingrese su nombre de usuario");
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 150, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Contraseña: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        txtPassword.setToolTipText("Ingrese su contraseña");
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 150, 30));

        JbutCreate.setText("Crear ");
        JbutCreate.setToolTipText("Presione para crear el nuevo usuario");
        JbutCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbutCreateActionPerformed(evt);
            }
        });
        getContentPane().add(JbutCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 70, -1));

        JbutNuevo.setText("Nuevo");
        JbutNuevo.setToolTipText("Presione para crear un nuevo usuario");
        getContentPane().add(JbutNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 190, 80, -1));

        JbutReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/espe/edu/imagenes/returns.png"))); // NOI18N
        JbutReturn.setToolTipText("Presione para volver al menu anterior");
        JbutReturn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JbutReturn.setBorderPainted(false);
        JbutReturn.setContentAreaFilled(false);
        JbutReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbutReturnActionPerformed(evt);
            }
        });
        getContentPane().add(JbutReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 50, 40));

        JbutExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/espe/edu/imagenes/exit.png"))); // NOI18N
        JbutExit.setToolTipText("Presione para salir del sistema");
        JbutExit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JbutExit.setBorderPainted(false);
        JbutExit.setContentAreaFilled(false);
        JbutExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbutExitActionPerformed(evt);
            }
        });
        getContentPane().add(JbutExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 40, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/espe/edu/imagenes/fondo verde.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JbutReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbutReturnActionPerformed
        JfrmMenuAdmin jfrmMenuAdmin = new JfrmMenuAdmin();
        jfrmMenuAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JbutReturnActionPerformed

    private void JbutExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbutExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_JbutExitActionPerformed

    private void JbutCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbutCreateActionPerformed
        IPersonal proyecto = new IPersonal();
        String username = txtName.getText();
        String password = txtPassword.getText();
        proyecto.create(username, password);
    }//GEN-LAST:event_JbutCreateActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfrmCreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfrmCreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfrmCreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfrmCreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfrmCreateUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbutCreate;
    private javax.swing.JButton JbutExit;
    private javax.swing.JButton JbutNuevo;
    private javax.swing.JButton JbutReturn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables
}
